Revert "arm64: mm: ensure that the zero page is visible to the page table walker"
Error: missing immediate expression at operand 1 -- `dsb '

This reverts commit c8f487a49a527990b29795f22884c3af02b94d97.